name: GIF Komunikaty

on:
  schedule:
    - cron: '5 22 * * *'

  workflow_dispatch:

jobs:
  build_gif_komunikaty:
    runs-on: ubuntu-latest
    name: GIF Komunikaty
    env:
      TEST_CHANNEL_URL: "@DamianTestChannel"

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: python script run
        run: |
          python test-script-3.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GIVEN_DATE: today
          FEED_NAME: GIF Komunikaty
          ARTICLE_TYPE: Komunikat
          FEED_URL: https://www.gov.pl/web/gif/komunikaty
          CHANNEL_URL: ${{ env.TEST_CHANNEL_URL }}
          TEST_CHANNEL_URL: ${{ env.TEST_CHANNEL_URL }}